Repository coder/registry, pull requests merged in 2025-09, with the labels that each got.

#375 feat: add conda support to JFrog modules
  registry/coder/modules/jfrog-oauth/README.md
  registry/coder/modules/jfrog-oauth/conda.conf.tftpl
  registry/coder/modules/jfrog-oauth/main.test.ts
  registry/coder/modules/jfrog-oauth/main.tf
  registry/coder/modules/jfrog-oauth/run.sh
  registry/coder/modules/jfrog-token/README.md
  registry/coder/modules/jfrog-token/conda.conf.tftpl
  registry/coder/modules/jfrog-token/main.test.ts
  registry/coder/modules/jfrog-token/main.tf
  registry/coder/modules/jfrog-token/run.sh
Labels: 🙋 Bounty claim

#408 chore: mark AMP CLI agent as verified
  registry/coder-labs/modules/sourcegraph-amp/README.md
Labels: version:patch

#414 Add maven package manager support to JFrog modules
  registry/coder/modules/jfrog-oauth/README.md
  registry/coder/modules/jfrog-oauth/main.test.ts
  registry/coder/modules/jfrog-oauth/main.tf
  registry/coder/modules/jfrog-oauth/run.sh
  registry/coder/modules/jfrog-oauth/settings.xml.tftpl
  registry/coder/modules/jfrog-token/README.md
  registry/coder/modules/jfrog-token/main.test.ts
  registry/coder/modules/jfrog-token/main.tf
  registry/coder/modules/jfrog-token/run.sh
  registry/coder/modules/jfrog-token/settings.xml.tftpl
Labels: version:minor, 🙋 Bounty claim

#362 feat: refactor Amazon Q module to use agentAPI
  registry/coder/.images/amazon-q.png
  registry/coder/modules/amazon-q/README.md
  registry/coder/modules/amazon-q/amazon-q.tftest.hcl
  registry/coder/modules/amazon-q/main.test.ts
  registry/coder/modules/amazon-q/main.tf
  registry/coder/modules/amazon-q/scripts/install.sh
  registry/coder/modules/amazon-q/scripts/start.sh
  registry/coder/modules/amazon-q/templates/agent-config.json.tpl
Labels: version:major, 🙋 Bounty claim
