Repository coder/registry, pull requests merged in 2025-08, with the labels that each got.

#275 fix: update HCP vault links to use current URL patterns
  registry/coder/modules/hcp-vault-secrets/README.md
Labels: version:patch

#272 chore: polish some modules readme
  registry/coder/modules/agentapi/README.md
  registry/coder/modules/aider/README.md
  registry/coder/modules/amazon-q/README.md
Labels: version:patch

#283 fix(claude-code): workaround for a coder bug
  registry/coder/modules/claude-code/README.md
  registry/coder/modules/claude-code/main.tf
Labels: version:patch

#248 fix/amazon-q mcp integration
  registry/coder/modules/amazon-q/main.tf
Labels: version:patch

#298 fix(claude-code): revert workaround
  registry/coder/modules/claude-code/README.md
  registry/coder/modules/claude-code/main.tf
Labels: version:patch

#297 feat(agentapi): Add support for running under a subdomain
  registry/coder/modules/agentapi/README.md
  registry/coder/modules/agentapi/main.test.ts
  registry/coder/modules/agentapi/main.tf
  registry/coder/modules/agentapi/scripts/main.sh
  registry/coder/modules/agentapi/test-util.ts
  registry/coder/modules/agentapi/testdata/agentapi-start.sh
Labels: version:minor

#303 chore: add description to JetBrains IDEs parameter
  registry/coder/modules/jetbrains/README.md
  registry/coder/modules/jetbrains/main.tf
Labels: version:patch

#299 feat: goose: add support for subdomain=false
  registry/coder/modules/goose/README.md
  registry/coder/modules/goose/main.test.ts
  registry/coder/modules/goose/main.tf
  registry/coder/modules/goose/testdata/agentapi-mock-print-args.js
Labels: version:minor

#321 chore: bump agentapi versions in the goose and gemini modules
  registry/coder-labs/modules/gemini/README.md
  registry/coder-labs/modules/gemini/main.tf
  registry/coder/modules/goose/README.md
  registry/coder/modules/goose/main.tf
Labels: version:patch

#317 feat(zed): settings input and MCP servers example
  registry/coder/modules/zed/README.md
  registry/coder/modules/zed/main.tf
Labels: version:minor

#329 Add Proxmox-Vm template
  .icons/proxmox.svg
  registry/umair/.images/avatar.jpeg
  registry/umair/README.md
  registry/umair/templates/proxmox-vm/README.md
  registry/umair/templates/proxmox-vm/cloud-init/user-data.tftpl
  registry/umair/templates/proxmox-vm/main.tf
Labels: 🙋 Bounty claim

#257 feat: Sourcegraph Amp module
  .icons/sourcegraph-amp.svg
  registry/coder-labs/modules/sourcegraph_amp/README.md
  registry/coder-labs/modules/sourcegraph_amp/main.test.ts
  registry/coder-labs/modules/sourcegraph_amp/main.tf
  registry/coder-labs/modules/sourcegraph_amp/scripts/install.sh
  registry/coder-labs/modules/sourcegraph_amp/scripts/start.sh
  registry/coder-labs/modules/sourcegraph_amp/testdata/amp-mock.sh
Labels: 🙋 Bounty claim

#387 feat(claude-code): add subdomain variable and logic
  registry/coder/modules/claude-code/README.md
  registry/coder/modules/claude-code/main.tf
Labels: version:minor

#228 feat(pgadmin): add new module for pgAdmin
  .icons/pgadmin.svg
  registry/AJ0070/.images/avatar.jpeg
  registry/AJ0070/README.md
  registry/AJ0070/modules/pgadmin/README.md
  registry/AJ0070/modules/pgadmin/main.test.ts
  registry/AJ0070/modules/pgadmin/main.tf
  registry/AJ0070/modules/pgadmin/run.sh
Labels: 🙋 Bounty claim

#355 feat: add digitalocean region module
  registry/umair/modules/digitalocean-region/README.md
  registry/umair/modules/digitalocean-region/main.test.ts
  registry/umair/modules/digitalocean-region/main.tf
Labels: 🙋 Bounty claim

#367 feat: add linode vm template
  .github/typos.toml
  .icons/akamai.svg
  registry/umair/templates/linode-vm/README.md
  registry/umair/templates/linode-vm/cloud-init/cloud-config.yaml.tftpl
  registry/umair/templates/linode-vm/main.tf
Labels: 🙋 Bounty claim
