Repository coder/registry, pull requests merged in 2025-07, with the labels that each got.

#160 feat(modules/claude-code): make the module ready for Coder Tasks
  registry/coder/modules/claude-code/README.md
  registry/coder/modules/claude-code/main.test.ts
  registry/coder/modules/claude-code/main.tf
  registry/coder/modules/claude-code/scripts/agentapi-start.sh
  registry/coder/modules/claude-code/scripts/agentapi-wait-for-start.sh
  registry/coder/modules/claude-code/scripts/remove-last-session-id.js
  registry/coder/modules/claude-code/testdata/agentapi-mock.js
  registry/coder/modules/claude-code/testdata/claude-mock.js
  registry/coder/modules/claude-code/testdata/coder-mock.js
  test/test.ts
Labels: version:major

#169 chore: update RDP modules display names, icon and docs
  .icons/rdp.svg
  MAINTAINER.md
  registry/coder/modules/local-windows-rdp/README.md
  registry/coder/modules/windows-rdp/README.md
Labels: version:patch

#167 fix(jetbrains-gateway) add agent id to url
  registry/coder/modules/jetbrains-gateway/README.md
  registry/coder/modules/jetbrains-gateway/main.test.ts
  registry/coder/modules/jetbrains-gateway/main.tf
Labels: version:patch

#151 feat(dotfiles): add custom variable for the dotfiles parameter description
  registry/coder/modules/dotfiles/README.md
  registry/coder/modules/dotfiles/main.tf
Labels: version:minor

#197 feat: add `--depth` to git-clone module to support shallow clones
  registry/coder/modules/git-clone/README.md
  registry/coder/modules/git-clone/main.tf
  registry/coder/modules/git-clone/run.sh
Labels: version:minor

#247 chore: bump agentapi version to v0.2.3
  registry/coder/modules/claude-code/README.md
  registry/coder/modules/claude-code/main.tf
Labels: version:patch

#229 feat: tmux module
  .gitignore
  .icons/tmux.svg
  registry/anomaly/.images/avatar.jpeg
  registry/anomaly/README.md
  registry/anomaly/modules/tmux/README.md
  registry/anomaly/modules/tmux/main.test.ts
  registry/anomaly/modules/tmux/main.tf
  registry/anomaly/modules/tmux/scripts/run.sh
  registry/anomaly/modules/tmux/scripts/start.sh
Labels: 🙋 Bounty claim

#246 feat: gemini cli module
  .icons/gemini.svg
  registry/coder-labs/modules/gemini/README.md
  registry/coder-labs/modules/gemini/main.test.ts
  registry/coder-labs/modules/gemini/main.tf
  registry/coder-labs/modules/gemini/scripts/install.sh
  registry/coder-labs/modules/gemini/scripts/start.sh
  registry/coder-labs/modules/gemini/testdata/gemini-mock.sh
Labels: 🙋 Bounty claim
